import type { Metadata } from "next";
import "./globals.css";
import Sidebar from "@/Components/Sidebar";
import { Inter } from "next/font/google";

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${inter.variable} antialiased min-h-screen w-full h-full flex`}
      >
        <nav className="h-screen w-[5%] sticky top-0">
         <Sidebar />
        </nav>
        <main className="bg-[#FFFAF2] h-full w-screen px-[24px] py-[22px]">
        {children}
        </main>
      </body>
    </html>
  );
}
